/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminIndustryDemandRouteImport } from './routes/admin.industry-demand'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSkillGapsRouteImport } from './routes/admin.skill-gaps'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAssessmentRouteImport } from './routes/dashboard.assessment'
import { Route as DashboardCareersRouteImport } from './routes/dashboard.careers'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardLearningPathRouteImport } from './routes/dashboard.learning-path'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardSkillGapRouteImport } from './routes/dashboard.skill-gap'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard.skills'
import { Route as DashboardTrendsRouteImport } from './routes/dashboard.trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndustryDemandRoute = AdminIndustryDemandRouteImport.update({
  id: '/industry-demand',
  path: '/industry-demand',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillGapsRoute = AdminSkillGapsRouteImport.update({
  id: '/skill-gaps',
  path: '/skill-gaps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssessmentRoute = DashboardAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLearningPathRoute = DashboardLearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillGapRoute = DashboardSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrendsRoute = DashboardTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/industry-demand': typeof AdminIndustryDemandRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/skill-gaps': typeof AdminSkillGapsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/learning-path': typeof DashboardLearningPathRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/industry-demand': typeof AdminIndustryDemandRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/skill-gaps': typeof AdminSkillGapsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/learning-path': typeof DashboardLearningPathRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/industry-demand': typeof AdminIndustryDemandRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/skill-gaps': typeof AdminSkillGapsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/dashboard/assessment': typeof DashboardAssessmentRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/learning-path': typeof DashboardLearningPathRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/courses'
    | '/admin/industry-demand'
    | '/admin/reports'
    | '/admin/skill-gaps'
    | '/admin/students'
    | '/dashboard/assessment'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/learning-path'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/skill-gap'
    | '/dashboard/skills'
    | '/dashboard/trends'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/courses'
    | '/admin/industry-demand'
    | '/admin/reports'
    | '/admin/skill-gaps'
    | '/admin/students'
    | '/dashboard/assessment'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/learning-path'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/skill-gap'
    | '/dashboard/skills'
    | '/dashboard/trends'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/courses'
    | '/admin/industry-demand'
    | '/admin/reports'
    | '/admin/skill-gaps'
    | '/admin/students'
    | '/dashboard/assessment'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/learning-path'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/skill-gap'
    | '/dashboard/skills'
    | '/dashboard/trends'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industry-demand': {
      id: '/admin/industry-demand'
      path: '/industry-demand'
      fullPath: '/admin/industry-demand'
      preLoaderRoute: typeof AdminIndustryDemandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skill-gaps': {
      id: '/admin/skill-gaps'
      path: '/skill-gaps'
      fullPath: '/admin/skill-gaps'
      preLoaderRoute: typeof AdminSkillGapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assessment': {
      id: '/dashboard/assessment'
      path: '/assessment'
      fullPath: '/dashboard/assessment'
      preLoaderRoute: typeof DashboardAssessmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/learning-path': {
      id: '/dashboard/learning-path'
      path: '/learning-path'
      fullPath: '/dashboard/learning-path'
      preLoaderRoute: typeof DashboardLearningPathRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skill-gap': {
      id: '/dashboard/skill-gap'
      path: '/skill-gap'
      fullPath: '/dashboard/skill-gap'
      preLoaderRoute: typeof DashboardSkillGapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trends': {
      id: '/dashboard/trends'
      path: '/trends'
      fullPath: '/dashboard/trends'
      preLoaderRoute: typeof DashboardTrendsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminIndustryDemandRoute: typeof AdminIndustryDemandRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSkillGapsRoute: typeof AdminSkillGapsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminIndustryDemandRoute: AdminIndustryDemandRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSkillGapsRoute: AdminSkillGapsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAssessmentRoute: typeof DashboardAssessmentRoute
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLearningPathRoute: typeof DashboardLearningPathRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardSkillGapRoute: typeof DashboardSkillGapRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardTrendsRoute: typeof DashboardTrendsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssessmentRoute: DashboardAssessmentRoute,
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLearningPathRoute: DashboardLearningPathRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardSkillGapRoute: DashboardSkillGapRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardTrendsRoute: DashboardTrendsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
